using System;
using System.IO;

namespace MangaManager
{
    /// <summary>
    /// Extracts JPEG/PNG image records from a MOBI (PalmDB) file.
    /// Works with standard MOBI files generated by KCC.
    /// </summary>
    internal static class MobiExtractor
    {
        public static string? ExtractToTemp(string mobiPath)
        {
            try
            {
                byte[] data = File.ReadAllBytes(mobiPath);

                // PalmDB: numRecords at offset 76 (uint16 big-endian)
                if (data.Length < 82) return null;
                int numRecords = ReadU16(data, 76);
                if (numRecords < 2) return null;

                // Record offsets: list starts at 78, each entry = 8 bytes
                int[] offsets = new int[numRecords + 1];
                for (int i = 0; i < numRecords; i++)
                    offsets[i] = (int)ReadU32(data, 78 + i * 8);
                offsets[numRecords] = data.Length; // sentinel

                // Record 0 = MOBI header
                int r0 = offsets[0];
                if (data.Length < r0 + 132) return null;

                // Verify "MOBI" magic at r0+16
                if (data[r0 + 16] != 'M' || data[r0 + 17] != 'O' ||
                    data[r0 + 18] != 'B' || data[r0 + 19] != 'I')
                    return null;

                // First image record index is at MOBI header offset 92
                // MOBI header starts at r0+16, so: r0+16+92 = r0+108
                uint firstImage = ReadU32(data, r0 + 108);
                if (firstImage == 0xFFFFFFFF || firstImage >= (uint)numRecords)
                    return null;

                // Create a clean temp dir named after the file
                string tempDir = Path.Combine(Path.GetTempPath(),
                    "MangaManager_" + Path.GetFileNameWithoutExtension(mobiPath));

                // Wipe stale extractions
                if (Directory.Exists(tempDir))
                    Directory.Delete(tempDir, true);
                Directory.CreateDirectory(tempDir);

                int imgCount = 0;
                for (int i = (int)firstImage; i < numRecords; i++)
                {
                    int start = offsets[i];
                    int end   = offsets[i + 1];
                    int len   = end - start;
                    if (len < 4) break;

                    if (!IsImage(data, start)) break; // stop at first non-image record

                    string ext     = ImageExt(data, start);
                    string imgFile = Path.Combine(tempDir, $"page{imgCount + 1:D4}{ext}");

                    using var fs = File.Create(imgFile);
                    fs.Write(data, start, len);
                    imgCount++;
                }

                return imgCount > 0 ? tempDir : null;
            }
            catch { return null; }
        }

        // ── Helpers ───────────────────────────────────────────────────────────
        private static bool IsImage(byte[] d, int o) =>
            IsJpeg(d, o) || IsPng(d, o) || IsGif(d, o);

        private static string ImageExt(byte[] d, int o) =>
            IsJpeg(d, o) ? ".jpg" :
            IsPng(d, o)  ? ".png" :
                           ".gif";

        private static bool IsJpeg(byte[] d, int o) =>
            o + 2 <= d.Length && d[o] == 0xFF && d[o + 1] == 0xD8;

        private static bool IsPng(byte[] d, int o) =>
            o + 4 <= d.Length && d[o] == 0x89 && d[o + 1] == 0x50 &&
            d[o + 2] == 0x4E && d[o + 3] == 0x47;

        private static bool IsGif(byte[] d, int o) =>
            o + 3 <= d.Length && d[o] == 0x47 && d[o + 1] == 0x49 && d[o + 2] == 0x46;

        private static uint ReadU32(byte[] d, int o) =>
            ((uint)d[o] << 24) | ((uint)d[o + 1] << 16) |
            ((uint)d[o + 2] << 8) | d[o + 3];

        private static ushort ReadU16(byte[] d, int o) =>
            (ushort)((d[o] << 8) | d[o + 1]);
    }
}
