using System;
using System.IO;

namespace MangaManager
{
    /// <summary>
    /// Extracts JPEG/PNG image records from a MOBI (PalmDB) file.
    /// Works with standard MOBI files generated by KCC.
    /// </summary>
    internal static class MobiExtractor
    {
        /// <summary>Extracts to a temporary directory (auto-named). Returns path or null.</summary>
        public static string? ExtractToTemp(string mobiPath)
        {
            string tempDir = Path.Combine(Path.GetTempPath(),
                "MangaManager_" + Path.GetFileNameWithoutExtension(mobiPath));

            if (Directory.Exists(tempDir)) Directory.Delete(tempDir, true);
            Directory.CreateDirectory(tempDir);

            int count = ExtractImages(mobiPath, tempDir);
            return count > 0 ? tempDir : null;
        }

        /// <summary>Extracts images directly into destFolder. Returns number of images written.</summary>
        public static int ExtractTo(string mobiPath, string destFolder)
        {
            Directory.CreateDirectory(destFolder);
            return ExtractImages(mobiPath, destFolder);
        }

        private static int ExtractImages(string mobiPath, string destFolder)
        {
            try
            {
                byte[] data = File.ReadAllBytes(mobiPath);

                if (data.Length < 82) return 0;
                int numRecords = ReadU16(data, 76);
                if (numRecords < 2) return 0;

                int[] offsets = new int[numRecords + 1];
                for (int i = 0; i < numRecords; i++)
                    offsets[i] = (int)ReadU32(data, 78 + i * 8);
                offsets[numRecords] = data.Length;

                int r0 = offsets[0];
                if (data.Length < r0 + 132) return 0;

                if (data[r0 + 16] != 'M' || data[r0 + 17] != 'O' ||
                    data[r0 + 18] != 'B' || data[r0 + 19] != 'I')
                    return 0;

                uint firstImage = ReadU32(data, r0 + 108);
                if (firstImage == 0xFFFFFFFF || firstImage >= (uint)numRecords)
                    return 0;

                int imgCount = 0;
                for (int i = (int)firstImage; i < numRecords; i++)
                {
                    int start = offsets[i];
                    int end   = offsets[i + 1];
                    int len   = end - start;
                    if (len < 4) break;
                    if (!IsImage(data, start)) break;

                    string imgFile = Path.Combine(destFolder, $"page{imgCount + 1:D4}{ImageExt(data, start)}");
                    using var fs = File.Create(imgFile);
                    fs.Write(data, start, len);
                    imgCount++;
                }

                return imgCount;
            }
            catch { return 0; }
        }

        // ── Helpers ───────────────────────────────────────────────────────────
        private static bool IsImage(byte[] d, int o) =>
            IsJpeg(d, o) || IsPng(d, o) || IsGif(d, o);

        private static string ImageExt(byte[] d, int o) =>
            IsJpeg(d, o) ? ".jpg" :
            IsPng(d, o)  ? ".png" :
                           ".gif";

        private static bool IsJpeg(byte[] d, int o) =>
            o + 2 <= d.Length && d[o] == 0xFF && d[o + 1] == 0xD8;

        private static bool IsPng(byte[] d, int o) =>
            o + 4 <= d.Length && d[o] == 0x89 && d[o + 1] == 0x50 &&
            d[o + 2] == 0x4E && d[o + 3] == 0x47;

        private static bool IsGif(byte[] d, int o) =>
            o + 3 <= d.Length && d[o] == 0x47 && d[o + 1] == 0x49 && d[o + 2] == 0x46;

        private static uint ReadU32(byte[] d, int o) =>
            ((uint)d[o] << 24) | ((uint)d[o + 1] << 16) |
            ((uint)d[o + 2] << 8) | d[o + 3];

        private static ushort ReadU16(byte[] d, int o) =>
            (ushort)((d[o] << 8) | d[o + 1]);
    }
}
